blueprint:
  name: AWTRIX NG App - Current Temperature - Clear
  domain: script
  source_url: https://github.com/phillc/ha-blueprints/blob/main/blueprints/script/awtrix-ng/awtrix_ng_app_current_temperature_clear.yaml
  author: phillc
  input:
    awtrix_id:
      name: AWTRIX NG Device
      selector:
        device:
          filter:
            - model: AWTRIX NG

variables:
  awtrix_id: !input awtrix_id
  awtrix_entities: "{{ device_entities(awtrix_id) }}"
  awtrix_topic: "{{ awtrix_entities | select('search', 'mqtt_prefix') | first }}"
  awtrix_topic_id: "{{ states(awtrix_topic) }}"
  
sequence:
  - action: mqtt.publish
    data:
      topic: "{{ awtrix_topic_id }}/cmd/apps/pushed/current_temperature"
