blueprint:
  name: AWTRIX NG Settings
  domain: script
  source_url: https://github.com/phillc/ha-blueprints/blob/main/blueprints/script/awtrix-ng/awtrix_ng_settings.yaml
  author: phillc

fields:
  awtrix_id:
    name: Device
    selector:
      device:
        filter:
          - model: AWTRIX NG
    required: true
  TMODE:
    selector:
      select:
        multiple: false
        mode: list
        options:
          - unset
          - "0"
          - "1"
          - "2"
          - "3"
          - "4"
          - "5"
          - "6"
    required: true
    description: "Changes the time app style."
    default: unset
  TFORMAT:
    selector:
      select:
        multiple: false
        mode: list
        options:
          - unset
          - "%H:%M:%S"
          - "%l:%M:%S"
          - "%H:%M"
          - "%H %M"
          - "%l:%M"
          - "%l %M"
          - "%l:%M %p"
          - "%l %M %p"
    required: true
    default: unset
  TIM:
    selector:
      select:
        multiple: false
        mode: list
        options:
          - unset
          - "true"
          - "false"
    required: true
    default: unset
  DAT:
    selector:
      select:
        multiple: false
        mode: list
        options:
          - unset
          - "true"
          - "false"
    required: true
    default: unset
  HUM:
    selector:
      select:
        multiple: false
        mode: list
        options:
          - unset
          - "true"
          - "false"
    required: true
    default: unset
  TEMP:
    selector:
      select:
        multiple: false
        mode: list
        options:
          - unset
          - "true"
          - "false"
    required: true
    default: unset
  BAT:
    selector:
      select:
        multiple: false
        mode: list
        options:
          - unset
          - "true"
          - "false"
    required: true
    description: "Enable or disable the native battery app in the app loop."
    default: unset
  WD:
    selector:
      select:
        multiple: false
        mode: list
        options:
          - unset
          - "true"
          - "false"
    required: true
    description: "Enable or disable the weekday display."
    default: unset

variables:
  awtrix_entities: "{{ device_entities(awtrix_id) }}"
  awtrix_topic: "{{ awtrix_entities | select('search', 'mqtt_prefix') | first }}"
  awtrix_topic_id: "{{ states(awtrix_topic) }}"
  raw_strings:
    timeMode: "{{ TMODE }}"
  raw_apps:
    Time: "{{ TIM }}"
    Date: "{{ DAT }}"
    Humidity: "{{ HUM }}"
    Temperature: "{{ TEMP }}"
    Battery: "{{ BAT }}"

sequence:
  - action: mqtt.publish
    data:
      topic: "{{ awtrix_topic_id }}/cmd/settings"
      payload: |-
        {%- set ns = namespace(out={}) %}
        {%- for k, v in raw_strings.items() if v != 'unset' %}
          {% set ns.out = combine(ns.out, { k: v }) %}
        {%- endfor %}
        {%- if WD != 'unset' %}
          {% set ns.out = combine(ns.out, {'weekdayBar': {'show': WD == 'true'}}) %}
        {%- endif %}
        {%- if TFORMAT != 'unset' %}
          {%- set formats = {
            '%H:%M:%S': {'time24h': true, 'timeShowSeconds': true, 'timeShowAmPm': false},
            '%l:%M:%S': {'time24h': false, 'timeShowSeconds': true, 'timeShowAmPm': false},
            '%H:%M': {'time24h': true, 'timeShowSeconds': false, 'timeShowAmPm': false},
            '%H %M': {'time24h': true, 'timeShowSeconds': false, 'timeShowAmPm': false},
            '%l:%M': {'time24h': false, 'timeShowSeconds': false, 'timeShowAmPm': false},
            '%l %M': {'time24h': false, 'timeShowSeconds': false, 'timeShowAmPm': false},
            '%l:%M %p': {'time24h': false, 'timeShowSeconds': false, 'timeShowAmPm': true},
            '%l %M %p': {'time24h': false, 'timeShowSeconds': false, 'timeShowAmPm': true}
          } %}
          {% set ns.out = combine(ns.out, formats[TFORMAT]) %}
        {%- endif %}
        {{ ns.out | tojson }}
  - if: "{{ raw_apps.values() | reject('eq', 'unset') | list | count > 0 }}"
    then:
      - action: mqtt.publish
        data:
          topic: "{{ awtrix_topic_id }}/cmd/apps/order"
          payload: |-
            {%- set ns = namespace(order=[], disabled=[]) %}
            {%- for name, enabled in raw_apps.items() if enabled != 'unset' %}
              {%- if enabled == 'true' %}
                {% set ns.order = ns.order + [name] %}
              {%- else %}
                {% set ns.disabled = ns.disabled + [name] %}
              {%- endif %}
            {%- endfor %}
            {{ {'order': ns.order, 'disabled': ns.disabled} | tojson }}
