blueprint:
  name: AWTRIX NG Notify
  domain: script
  source_url: https://github.com/phillc/ha-blueprints/blob/main/blueprints/script/awtrix-ng/awtrix_ng_notify.yaml
  author: phillc

fields:
  awtrix_id:
    name: Device
    selector:
      device:
        filter:
          - model: AWTRIX NG
    required: true
  text:
    selector:
      text:
    name: text
    required: true

variables:
  awtrix_entities: "{{ device_entities(awtrix_id) }}"
  awtrix_topic: "{{ awtrix_entities | select('search', 'mqtt_prefix') | first }}"
  awtrix_topic_id: "{{ states(awtrix_topic) }}"

sequence:
  - action: mqtt.publish
    data:
      topic: "{{ awtrix_topic_id }}/cmd/notify"
      payload: >-
        {% set output = {"text": text} %}
        {{ output | to_json(sort_keys=True) }}
