blueprint:
  name: Notify on Valve Change
  domain: automation
  source_url: https://github.com/phillc/ha-blueprints/blob/main/automations/notify_on_valve_change.yaml
  author: phillc

  input:
    valve_id:
      name: Water Valve
      selector:
        device:
          filter:
            - domain: "switch"
              model: "ZAC36"
    notification_targets:
      name: Notification Targets
      selector:
        target:
          filter:
            - domain: "device"
            
triggers:
  - trigger: state
    entity_id: !input valve_id

actions:
  - action: notify.notify
    target: !input notification_targets
    title: "Water Valve Change"
    message: "The water valve has been changed to {{ state(valve_id) }}"