blueprint:
  name: Awtrix App - Calendar Event - Update
  domain: script
  source_url: https://github.com/phillc/ha-blueprints/blob/main/scripts/awtrix_app_calendar_event_update.yaml
  author: phillc
  
fields:
  awtrix_id:
    name: Device
    selector:
      device:
        filter:
          - model: AWTRIX 3
    required: true
  calendar_id:
    name: Calendar
    selector:
      entity:
        filter:
          - domain: calendar
    required: true

variables:
  awtrix_entities: "{{ device_entities(awtrix_id) }}"
  awtrix_topic: "{{ awtrix_entities | select('search', 'device_topic') | first }}"
  awtrix_topic_id: "{{ states(awtrix_topic) }}"
  text: "{{ state_attr(calendar_id, 'message') }}"
  start_time: "{{ state_attr(calendar_id, 'start_time') }}"
  prefix: >-
    {% if (start_time | as_datetime | as_local) < today_at("23:59") %}
      Today
    {% else %}
      {{ time_until(start_time | as_datetime) }}
    {% endif %}

sequence:
  - action: mqtt.publish
    data:
      topic: "{{ awtrix_topic_id }}/custom/calendar_event"
      payload: >-
        {% set output = {"text": "{{ prefix }}: {{ text }}", "icon": "230", "pushIcon": 2} %}
        {{ output | to_json(sort_keys=True) }}
