blueprint:
  name: Awtrix App - Calendar Event - Update
  domain: script
  source_url: https://github.com/phillc/ha-blueprints/blob/main/scripts/awtrix_app_calendar_event_update.yaml

  input:
    device_id:
      name: Device
      selector:
        device:
          filter:
            - model: AWTRIX 3
    calendar_id:
      name: Calendar
      selector:
        entity:
          filter:
            - domain: calendar
variables:
  device_id: !input device_id
  device_entities: "{{ device_entities(device_id) }}"
  device_topic: "{{ (device_entities | select('search','device_topic') | list)[0] }}"
  device_topic_id: "{{ states(device_topic) }}"
  text: "{{ state_attr(calendar_id, 'message') }}"
  start_time: "{{ state_attr(calendar_id, 'start_time') }}"
  prefix: >-
    {% if (start_time | as_datetime | as_local) < today_at("23:59") %}
      Today
    {% else %}
      {{ time_until(start_time | as_datetime) }}
    {% endif %}
sequence:
  - action: mqtt.publish
    data:
      topic: "{{ device_topic_id }}/custom/calendar_event"
      payload: '{"text": "{{ prefix }}: {{ text }}", "icon": "230", "pushIcon": 2}'
