blueprint:
  name: Awtrix App - Calendar Event - Clear
  domain: script
  source_url: https://github.com/phillc/ha-blueprints/blob/main/scripts/awtrix_app_calendar_event_clear.yaml

  input:
    device_id:
      name: Device
      selector:
        device:
          filter:
            - model: AWTRIX 3

variables:
  device_id: !input device_id
  device_entities: "{{ device_entities(device_id) }}"
  device_topic: "{{ (device_entities | select('search','device_topic') | list)[0] }}"
  device_topic_id: "{{ states(device_topic) }}"

sequence:
  - action: mqtt.publish
    data:
      topic: "{{ device_topic_id }}/custom/calendar_event"
