blueprint:
  name: Awtrix App - Current Temperature - Update
  domain: script
  source_url: https://github.com/phillc/ha-blueprints/blob/main/scripts/awtrix_app_current_temperature_update.yaml
  author: phillc

fields:
  awtrix_id:
    name: Device
    selector:
      device:
        filter:
          - model: AWTRIX 3
    required: true
  sensor_id:
    name: Sensor
    selector:
      entity:
        filter:
          - domain: sensor
            device_class: temperature
    required: true

variables:
  awtrix_entities: "{{ device_entities(awtrix_id) }}"
  awtrix_topic: "{{ awtrix_entities | select('search', 'device_topic') | first }}"
  awtrix_topic_id: "{{ states(awtrix_topic) }}"
  temperature: "{{ states(sensor_id) }}"

sequence:
  - action: mqtt.publish
    data:
      topic: "{{ awtrix_topic_id }}/custom/current_temperature"
      payload: '{"text": "{{ temperature }}°F", "icon": "3357", "pushIcon": 2}'
